### ISSUE TITLE
Error when deleting a map

### ISSUE THREAD

**Issue by hernanc** [saltstack/salt-cloud#902]
I've successfully created a map, when I tried to delete it it gave me this error:

# salt-cloud -m /data/salt-cloud/alpha.map -d
[INFO    ] salt-cloud starting
[INFO    ] Applying map from '/data/salt-cloud/alpha.map'.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'node-1.mydomain.com'
Traceback (most recent call last):
  File "/usr/local/bin/salt-cloud", line 14, in <module>
    main()
  File "/usr/local/bin/salt-cloud", line 10, in main
    cloud.run()
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cli.py", line 171, in run
    matching = mapper.delete_map(query='list_nodes')
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cloud.py", line 911, in delete_map
    query_map = self.interpolated_map(query=query)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cloud.py", line 894, in interpolated_map
    names.remove(vm_name)
KeyError: 'node-1.mydomain.com'
Traceback (most recent call last):
  File "/usr/local/bin/salt-cloud", line 14, in <module>
    main()
  File "/usr/local/bin/salt-cloud", line 10, in main
    cloud.run()
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cli.py", line 171, in run
    matching = mapper.delete_map(query='list_nodes')
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cloud.py", line 911, in delete_map
    query_map = self.interpolated_map(query=query)
  File "/usr/local/lib/python2.7/dist-packages/saltcloud/cloud.py", line 894, in interpolated_map
    names.remove(vm_name)
KeyError: 'node-1.mydomain.com'

**Comment by hernanc** [comment]
Hey thanks for the replies. I'm closing this one as it's very old. Reopen if necessary.
