### ISSUE TITLE
salt-cloud 'LibcloudError in None 'Could not find specified endpoint' error for openstack cloud provider

### ISSUE THREAD

**Issue by manan00** [saltstack/salt-cloud#934]
Hello, 

Can anyone help me with below error,

Salt cloud version
----------------------------------
salt-cloud --versions-report
Salt: 2015.5.3
Python: 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
Jinja2: 2.2.1
M2Crypto: 0.20.2
msgpack-python: 0.4.6
msgpack-pure: Not Installed
pycrypto: 2.0.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.3.1
RAET: Not Installed
ZMQ: 3.2.5
Mako: Not Installed
Tornado: Not Installed
Apache Libcloud: 0.17.0

List-providers works successfully, 

salt-cloud --list-providers
[INFO    ] salt-cloud starting
my-openstack-config:
    ----------
    openstack:
        ----------

When I try to list images, or list size or create a new VM I am getting below error

salt-cloud --list-images openstack
[INFO    ] salt-cloud starting
[ERROR   ] Failed to get the output of 'openstack.avail_images()': <LibcloudError in None 'Could not find specified endpoint'>
my-openstack-config:
    ----------

I tried running this in debug mode to get trace
	
[ERROR   ] Failed to get the output of 'openstack.avail_images()': <LibcloudError in None 'Could not find specified endpoint'>
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 841, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.6/site-packages/salt/cloud/libcloudfuncs.py", line 178, in avail_images
    images = conn.list_images()
  File "/usr/lib/python2.6/site-packages/libcloud/compute/drivers/openstack.py", line 226, in list_images
    self.connection.request('/images/detail').object, ex_only_active)
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack.py", line 201, in request
    raw=raw)
  File "/usr/lib/python2.6/site-packages/libcloud/common/base.py", line 657, in request
    action = self.morph_action_hook(action)
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack.py", line 256, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack.py", line 301, in _populate_hosts_and_request_paths
    url = self._ex_force_base_url or self.get_endpoint()
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack.py", line 241, in get_endpoint
    region=service_region)
  File "/usr/lib/python2.6/site-packages/libcloud/common/openstack_identity.py", line 279, in get_endpoint
    raise LibcloudError('Could not find specified endpoint')
LibcloudError: <LibcloudError in None 'Could not find specified endpoint'>
[DEBUG   ] LazyLoaded nested.output
my-openstack-config:
    ----------

**Comment by manan00** [comment]
I found this ticket on LibCloud https://issues.apache.org/jira/browse/LIBCLOUD-400 , however not sure what was the resolution.
